//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string ENGINE = "engine";
        
        public const string VACUUM = "vacuum";
        
        public const string MIRRORS = "mirrors";
        
        public const string PAWS = "paws";
        
        public const string IMPACT = "impact";
        
        public const string BRUSH = "brush";
        
        public const string LIGHT = "light";
    }
}
